name: mobile_app
description: A Flutter authentication app with SQLite and OTP verification.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  random_string: ^2.3.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  file_picker: ^10.1.2
  url_launcher: ^6.1.12
  supabase_flutter: 1.10.19

dependency_overrides:
  sign_in_with_apple: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
